#!/usr/bin/env bash

# path:       /usr/bin/instamenue_emoji
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/instamenu-extra
# date:       2021-03-10 12:34:47.440579

# Running ps to get running processes and display in instamenu.
selected="$(ps --user "$(id -u)" -F | \
            instamenu -c -i -l 20 -p "Search for process to kill:" | \
            awk '{print $2" "$11}')";

# Nested 'if' statements.  The outer 'if' statement is what to do
# when we select one of the 'selected' options listed in dmenu.
if [[ -n $selected ]]; then

    # Piping No/Yes into instamenu as a safety measure, in case you
    # select a process that you don't actually want killed.

    if imenu -c "Kill $selected?"; then
        selpid="$(awk '{print $1}' <<< "$selected")";
        kill -9 "$selpid"
		echo "Process $selected has been killed." && exit 0
    else
		echo "Program terminated." && exit 0
    fi
fi

exit 0
