#!/bin/sh

asksetting() {
    prefix="/bin/"
    options1=$(printf '%s\n' ${PATH//:/\/* } | grep "instamenu_" | sed '/path/d' | grep -oP "^$prefix\K.*")
    options2=$(printf '%s\n' ${PATH//:/\/* } | grep "instamenue_" | sed '/smartrun/d' | grep -oP "^$prefix\K.*")
    echo ">>h Select App to run
$options1
$options2" | instamenu -ps 1 -l 20 -w -400 -i -h -1 -y -1 -bw 4 -q "${1:-Search...}" -H -x 10000
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
    CHOICE="$(asksetting)"
    [ -n "$CHOICE" ] || exit
    unset LOOPSETTING
    case $CHOICE in
    instamenu*)
        $CHOICE &
        ;;
    *)
        echo "Program terminated." && exit
        ;;
    esac
done
