#!/bin/bash

# simple pacman GUI for instantOS

choicemenu() {
    echo ':g Install
:b 蓮Browse
:r Remove
:b Install AUR package
:b Update
:r Close' | instamenu -ps 1 -l 20 -w -400 -i -h -1 -y -1 -bw 4 -q  "${1:-insta_pacman...}" -H -x 10000
}

CHOICE="$(choicemenu)"

[ -n "$CHOICE" ] || exit

case "$CHOICE" in
*Install)
    PACKAGE="$(imenu -i 'enter package name')"
    [ -n "$PACKAGE" ] || exit
    echo "installing $PACKAGE"
    alacritty -e bash -c "(sudo pacman -S $PACKAGE) && notify-send 'finished installing '$PACKAGE"
    ;;
*Remove)
    PACKAGE="$(imenu -i 'enter package name')"
    [ -n "$PACKAGE" ] || exit
    alacritty -e bash -c "(sudo pacman -R $PACKAGE) && notify-send finished\ uninstalling\ $PACKAGE"
    ;;
*Browse)
    pamac-manager &
    exit
    ;;
*package)
    PACKAGE="$(imenu -i 'enter package name')"
    [ -n "$PACKAGE" ] || exit
    alacritty -e bash -c "(yay -S $PACKAGE) && notify-send 'finished installing '$PACKAGE"
    ;;
*Update)
    alacritty -e bash -c "(yay -Syyu) && notify-send 'finished updating'"
    ;;
*Close)
    instamenu_settings &
    ;;
esac
