#!/usr/bin/env bash

# path:       /usr/bin/instamenue_pacman
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/instamenu-extra
# date:       2021-01-03 12:34:47.440579

getsettings() {
    TERMINAL=$(gsettings get org.therepoclub.instamenu.preferences terminal | sed s/\'//g)
    WEBBROWSER=$(gsettings get org.therepoclub.instamenu.preferences webbrowser | sed s/\'//g)
    FILEMANAGER=$(gsettings get org.therepoclub.instamenu.preferences filemanager | sed s/\'//g)
    MAILREADER=$(gsettings get org.therepoclub.instamenu.preferences mailreader | sed s/\'//g)
    TEXTEDITOR=$(gsettings get org.therepoclub.instamenu.preferences texteditor | sed s/\'//g)
    HYPERVISOR=$(gsettings get org.therepoclub.instamenu.preferences hypervisor | sed s/\'//g)
    GITBROWSER=$(gsettings get org.therepoclub.instamenu.preferences gitbrowser | sed s/\'//g)
}

# simple pacman GUI for instantOS
getsettings
choicemenu() {
    options=":g Install
:b 蓮Browse
:r Remove
:b Install AUR package
:b Update
:r Close Pacman"

    echo "$options" | instamenu -ps 1 -l 20 -w -400 -i -h -1 -y -1 -bw 4 -q "${1:-Settings...}" -H -x 10000
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do

    CHOICE="$(choicemenu)"
    [ -n "$CHOICE" ] || exit
    case "$CHOICE" in
    *Install)
        PACKAGE="$(imenu -i 'enter package name')"
        [ -n "$PACKAGE" ] || echo "Program terminated." && exit
        echo "installing $PACKAGE"
        $TERMINAL -e bash -c "(sudo pacman -S $PACKAGE) && notify-send 'instamenue_pacman' 'finished installing '$PACKAGE"
        ;;
    *Remove)
        PACKAGE="$(imenu -i 'enter package name')"
        [ -n "$PACKAGE" ] || echo "Program terminated." && exit
        $TERMINAL -e bash -c "(sudo pacman -R $PACKAGE) && notify-send 'instamenue_pacman' 'finished uninstalling '$PACKAGE"
        ;;
    *Browse)
        octopi &
        echo "Program terminated." && exit
        ;;
    *package)
        PACKAGE="$(imenu -i 'enter package name')"
        [ -n "$PACKAGE" ] || echo "Program terminated." && exit
        $TERMINAL -e bash -c "(paru -S $PACKAGE) && notify-send 'instamenue_pacman' 'finished installing '$PACKAGE"
        ;;
    *Update)
        $TERMINAL -e bash -c "(paru -Syyu) && notify-send 'instamenue_pacman' 'finished updating'"
        ;;
    *Pacman)
        instamenue_settings &
        echo "Program terminated." && exit
        ;;
    esac
done
