#!/usr/bin/env bash

# path:       /usr/bin/instamenue_smartrun
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/instamenu-extra
# date:       2021-01-03 12:34:47.440579

asksetting() {
    options1=$(printf '%s\n' ${PATH//:/\/* } | grep "instamenu_" | sed 's|^.*/||g' | awk '!NF || !seen[$0]++')
    options2=$(printf '%s\n' ${PATH//:/\/* } | grep "instamenue_" | sed 's|^.*/||g' | awk '!NF || !seen[$0]++')
    echo -e ">>h Select App to run
$options1
$options2" | instamenu -ps 1 -l 20 -w -400 -i -h -1 -y -1 -bw 4 -q "${1:-Search...}" -x 10000
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
    CHOICE="$(asksetting)"
    [ -n "$CHOICE" ] || exit
    unset LOOPSETTING
    case $CHOICE in
    instamenu*)
        $CHOICE &
        ;;
    *)
        echo "Program terminated." && exit
        ;;
    esac
done
