#!/usr/bin/env bash

# path:       /usr/bin/repomenue_pacman
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/repomenu-extra
# date:       2021-01-03 12:34:47.440579

getsettings() {
    TERMINAL=$(gsettings get org.therepoclub.repomenu.preferences terminal | sed s/\'//g)
    WEBBROWSER=$(gsettings get org.therepoclub.repomenu.preferences webbrowser | sed s/\'//g)
    FILEMANAGER=$(gsettings get org.therepoclub.repomenu.preferences filemanager | sed s/\'//g)
    MAILREADER=$(gsettings get org.therepoclub.repomenu.preferences mailreader | sed s/\'//g)
    TEXTEDITOR=$(gsettings get org.therepoclub.repomenu.preferences texteditor | sed s/\'//g)
    HYPERVISOR=$(gsettings get org.therepoclub.repomenu.preferences hypervisor | sed s/\'//g)
    GITBROWSER=$(gsettings get org.therepoclub.repomenu.preferences gitbrowser | sed s/\'//g)
}

cleanup () {
    cleanPackages=()
    for p in $(pacman -Qtdq); do
        cleanPackages+="$p"
    done
    if [[ ! -z "$cleanPackages" ]]; then
        $TERMINAL -e bash -c "(sudo pacman -Rns $cleanPackages) && notify-send 'repomenue_pacman' 'finished installing '$PACKAGE"
    else
        $TERMINAL -e bash -c "notify-send 'Notice' 'No unused dependencies found!'"
    fi
}

# simple pacman GUI for instantOS
getsettings
choicemenu() {
    options=":g Install
:b 蓮Browse
:r Remove
:y Cleanup
:b Install AUR package
:b Update
:r Close Pacman"

    echo -e "$options" | repomenu -ps 1 -l 20 -w -400 -i -h -1 -y -1 -bw 4 -q "${1:-Settings...}" -x 10000
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do

    CHOICE="$(choicemenu)"
    [ -n "$CHOICE" ] || exit
    case "$CHOICE" in
    *Install)
        PACKAGE="$(imenu -i 'enter package name')"
        if [ -z "$PACKAGE" ]; then echo "Program terminated." && exit; fi
        echo "installing $PACKAGE"
        $TERMINAL -e bash -c "(sudo pacman -S $PACKAGE) && notify-send 'repomenue_pacman' 'finished installing '$PACKAGE"
        ;;
    *Remove)
        PACKAGE="$(imenu -i 'enter package name')"
        if [ -z "$PACKAGE" ]; then echo "Program terminated." && exit; fi
        $TERMINAL -e bash -c "(sudo pacman -R $PACKAGE) && notify-send 'repomenue_pacman' 'finished uninstalling '$PACKAGE"
        ;;
    *Browse)
        if pacman -Qs "octopi" > /dev/null ; then
            octopi &
        elif pacman -Qs "pamac" > /dev/null ; then
            pamac &
        elif pacman -Qs "pkgbrowser" > /dev/null ; then
            pkgbrowser &
        else
            $WEBBROWSER "https://archlinux.org/packages/"
        fi
        echo "Program terminated." && exit
        ;;
    *Cleanup)
        cleanup
        ;;
    *AUR*)
        PACKAGE="$(imenu -i 'enter package name')"
        if [ -z "$PACKAGE" ]; then echo "Program terminated." && exit; fi
        $TERMINAL -e bash -c "(instaaur -g $PACKAGE) && notify-send 'repomenue_pacman' 'finished installing '$PACKAGE"
        ;;
    *Update)
        $TERMINAL -e bash -c "(sudo pacman -Syyu) && notify-send 'repomenue_pacman' 'finished updating'"
        ;;
    *Pacman)
        repomenue_settings &
        echo "Program terminated." && exit
        ;;
    esac
done
