#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi
xdotool="xclip -sel clip"


STARTDIR=${PEOPLE_STORE_DIR-~/.contact-store}
BASEDIR=$STARTDIR
DONE=0
LEVEL=0
PREVSELECTION=""
SELECTION=""
EMAIL_FIELD='email'
ADDRESS_FIELD='address'

while [ "$DONE" -eq 0 ] ; do
    contact_files=( "$STARTDIR"/* )
    contact_files=( "${contact_files[@]#"$STARTDIR"/}" )
    contact_files=( "${contact_files[@]%.gpg}" )

    if [ "$LEVEL" -ne 0 ] ; then
        contact_files=(".." "${contact_files[@]}")
    fi
    entry=$(printf ':g  %s\n' "${contact_files[@]}" | repomenu "$@" -q "Search for a contact:" -c -ps 0 -l 10 -w -500 -i -h -1)
    entry=$(echo $entry | sed "s/:g  //")

    if [ -z "$entry" ] ; then
    DONE=1
    exit
    fi

    if [ "$entry" != ".." ] ; then
        PREVSELECTION=$SELECTION
        SELECTION="$SELECTION/$entry"

    # check if another dir
    if [ -d "$STARTDIR/$entry" ] ; then
        STARTDIR="$STARTDIR/$entry"
        LEVEL=$((LEVEL+1))
    else
        # not a directory so it must be a real contact entry

        if [[ $typeit -eq 0 ]]; then
            FIELDS=()
            PEOPLE=$(contacts show "$SELECTION" | head -1)
            OTHER=$(contacts show "$SELECTION" | awk -F: '(NR>1){ st = index($0,":");print $1 substr($0,st+1)}')
            FIELDS+=":r  Phone Number\n"
            if [ ! -z "${OTHER}" ]; then
                while read -r line; do
                    FIELD=$(echo -e "$line" | awk '{print $1}')
                    if [ "$FIELD" = "email" ]; then
                        FIELDS+=":g  ${FIELD^}\n"
                    elif [ "$FIELD" = "address" ]; then
                        FIELDS+=":b  ${FIELD^}\n"
                    else
                        FIELDS+=":p  ${FIELD^}\n"
                    fi
                done <<< "$OTHER"
            fi

            ENTRY_FIELD=$(echo -e "$FIELDS" | sed '/^$/d' | repomenu "$@" -q "Select a field:" -c -ps 0 -l 10 -w -400 -i -h -1)
            if [[ $ENTRY_FIELD = *'Phone Number' ]]; then
                PEOPLE=$(contacts show "$SELECTION" | sed "s/^[ \t]*//" | head -1)
                clipmenu-ctl disable
                if [ $(clipmenu-ctl status) == "enabled" ]; then
                    clipmenu-ctl disable
                else
                    echo -e "$PEOPLE" | $xdotool
                fi
                clipmenu-ctl enable
                if [ $(clipmenu-ctl status) == "disabled" ]; then
                    clipmenu-ctl enable
                fi
            elif [[ $ENTRY_FIELD = *'Email' ]]; then
                EMAIL=$(contacts show "$SELECTION" | grep "${EMAIL_FIELD}" | awk '{sub(/:/,"")}{print $2}1' | sed "s/^[ \t]*//" | head -1)
                clipmenu-ctl disable
                if [ $(clipmenu-ctl status) == "enabled" ]; then
                    clipmenu-ctl disable
                else
                    echo -e "$EMAIL" | $xdotool
                fi
                clipmenu-ctl enable
                if [ $(clipmenu-ctl status) == "disabled" ]; then
                    clipmenu-ctl enable
                fi
            elif [[ $ENTRY_FIELD = *'Address' ]]; then
                ADDRESS=$(contacts show "$SELECTION" | grep "${ADDRESS_FIELD}" | awk '{sub(/:/,"")}{print $2}1' | sed "s/^[ \t]*//" | head -1)
                clipmenu-ctl disable
                if [ $(clipmenu-ctl status) == "enabled" ]; then
                    clipmenu-ctl disable
                else
                    echo -e "$ADDRESS" | $xdotool
                fi
                clipmenu-ctl enable
                if [ $(clipmenu-ctl status) == "disabled" ]; then
                    clipmenu-ctl enable
                fi
            else
                CUSTOM_FIELD=$(echo -e "$ENTRY_FIELD" | awk 'NF>1 {sub("^[^A-Z]*","")} {print}')
                CUSTOM_FIELD=$(contacts show "$SELECTION" | grep "${CUSTOM_FIELD,,}" | awk '{sub(/:/,"")}{first = $1; $1=""; print $0;}1' | sed "s/^[ \t]*//" | head -1)
                clipmenu-ctl disable
                if [ $(clipmenu-ctl status) == "enabled" ]; then
                    clipmenu-ctl disable
                else
                    echo -e "$CUSTOM_FIELD" | $xdotool
                fi
                clipmenu-ctl enable
                if [ $(clipmenu-ctl status) == "disabled" ]; then
                    clipmenu-ctl enable
                fi
            fi
        else
            xdotool - <<<"type --clearmodifiers -- $(contacts show "$SELECTION" | head -n 1)"
        fi
        DONE=1
    fi

else
    LEVEL=$((LEVEL-1))
    SELECTION=$PREVSELECTION
    STARTDIR="$BASEDIR/$SELECTION"
  fi
done



