#!/usr/bin/env bash
# -*-coding:utf-8 -*-
# Auto updated?
#   Yes
#File :
#   repomenue_snapshots
#Author:
#   The-Repo-Club [wayne6324@gmail.com]
#Github:
#   https://github.com/The-Repo-Club/
#
# Created:
#   Thu 16 September 2021, 05:07:57 PM [GMT]
# Modified:
#   Fri 21 January 2022, 02:29:56 PM [GMT]
#
# Description:
#   <Todo>
#

mnt='/mnt/750GB/.snapshots'

## Script metadata
SCRIPTNAME=${0##*/}
VERSION="2021.09.19"
DESCRIPTION="A bach BTRFS Sanpshot wrapper"
AUTHOR="The-Repo-Club <wayne6324@gmail.com>"

## Set Colors (copied from makepkg)
ALL_OFF="\e[1;0m"
RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
BLUE="\e[1;34m"
PURPLE="\e[1:35m"
CYAN="\e[1:36m"

readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN

getsettings() {
  TERMINAL=$(repo-exec terminal)
}

asksetting() {
  commands=
  if command -v snaplist &>/dev/null; then
    commands+=":g Snaplist\n:r Snapremove\n"
  fi

  if command -v snaphome &>/dev/null; then
    commands+=":p Snaphome\n"
  fi

  if command -v snaproot &>/dev/null; then
    commands+=":r Snaproot\n"
  fi

  if command -v snapshot &>/dev/null; then
    commands+=":r שׂSnapshot\n"
  fi
  echo -e "$commands" | sed '/^$/d' | repomenu -c -l 10 -w -300 -i -h -1 -bw 4 -q "${1:-Select snap package...}"
}

cmd_snaplist() {
  pkexec snaplist "--menu" | repomenu -c -l 10 -w -300 -i -h -1 -bw 4 -q "${1:-Select snap package...}"
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
  CHOICE="$(asksetting)"
  [ -n "$CHOICE" ] || exit
  unset LOOPSETTING
  getsettings
  snap=$(echo $CHOICE | awk -F"Snap" '{print $2}')
  case "$CHOICE" in
  *list)
    cmd_snaplist
    ;;
  *remove)
    package=$(cmd_snaplist | awk '{print $2}')
    [ -n "$package" ] || exit
    pkexec btrfs subvolume delete $mnt/$package
    ;;
  *home)
    $TERMINAL --title snapper --class snapper,Snapper -e sudo snap$snap
    ;;
  *root)
    $TERMINAL --title snapper --class snapper,Snapper -e sudo snap$snap
    ;;
  *shot)
    $TERMINAL --title snapper --class snapper,Snapper -e sudo snap$snap
    ;;
  *)
    echo "Program terminated."
    exit 1
    ;;
  esac
done
