#!/usr/bin/env bash
#-*-coding:utf-8 -*-
#Auto updated?
#   Yes
#File :
#   repomenue_editor
#Author :
#   The-Repo-Club [wayne6324@gmail.com]
#Github :
#   https://github.com/The-Repo-Club/
#
#Created:
#   Wed 10 March 2021, 12:34:47 PM [GMT+1]
#Last edited:
#   Sun 17 July 2022, 03:11:08 PM [GMT+1]
#
#Description:
#   <Todo>
#
#Dependencies:
#   <None>
#

getsettings() {
  TERMINAL=$(repo-exec terminal)
  WEBBROWSER=$(repo-exec webbrowser)
  FILEMANAGER=$(repo-exec filemanager)
  MAILREADER=$(repo-exec mailreader)
  TEXTEDITOR=$(repo-exec texteditor)
  HYPERVISOR=$(repo-exec hypervisor)
  GITBROWSER=$(repo-exec gitbrowser)
}

asksetting() {
  options=$(ls "$HOME/.config/repomenu/scripts/")

  echo ">>h Work on which script
$options" | repomenu -c -l 10 -w -400 -i -h -1 -bw 4 -q "${1:-Search...}"
}

LOOPSETTING="true"
getsettings
while [ -n "$LOOPSETTING" ]; do
  FILE="$HOME/.config/repomenu/scripts/$(asksetting)"
  unset LOOPSETTING
  if [ -f "$FILE" ]; then
    $TEXTEDITOR "$FILE"
  else
    echo "Program terminated." && exit 1
  fi
done
