#!/usr/bin/env bash
# -*-coding:utf-8 -*-
# Auto updated?
#   Yes
#File :
#   repomenue_bm_remove
#Author :
#   The-Repo-Club [wayne6324:gmail.com]
#Github :
#   https://github.com/The-Repo-Club/
#
# Created:
#   Wed 10 March 2021, 12:34:47 PM [GMT]
# Last edited:
#   Thu 20 January 2022, 05:02:10 PM [GMT]
#
# Description:
#   <Todo>
#

declare -A g bmarray;

while IFS=\| read -r guid date id url title tags;
do
  bookmark="$title "-" "$url" "-" "$tags"";
  bmarray["$bookmark"]="$url";
done < "$HOME/.config/repomenu/bookmarks/bm.lnk"

function load() {
  while IFS=\| read -r guid date id url title tags;
  do
    bookmark="$title "-" "$url" "-" "$tags"";
    printf "$bookmark\n";
  done < "$HOME/.config/repomenu/bookmarks/bm.lnk"

}

choice=$(load | repomenu -i -l -400 -p "${1:-Remove a bookmark:...}")

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
  [ -n "$choice" ] || exit
  unset LOOPSETTING
  case "$choice" in
    *) bm -w "$HOME/.config/repomenu/bookmarks/" -d ${bmarray[$choice]} -D;;
  esac
done
