#!/usr/bin/env bash

# path:       /usr/bin/repomenue_bm_add
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/repomenu-extra
# date:       2021-03-10 12:34:47.440579

declare -A g bmarray;

while IFS=\| read -r guid date id url title tags;
do
  bookmark="$title "-" "$url" "-" "$tags"";
  bmarray["$bookmark"]="$url";
done < "$HOME/.config/repomenu/bookmarks/bm.lnk"

function load() {
  while IFS=\| read -r guid date id url title tags;
  do
    bookmark="$title "-" "$url" "-" "$tags"";
    printf "$bookmark\n";
  done < "$HOME/.config/repomenu/bookmarks/bm.lnk"

}

choice=$(load | repomenu -i -l -400 -p "${1:-Remove a bookmark:...}")

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
  [ -n "$choice" ] || exit
  unset LOOPSETTING
  case "$choice" in
    *) bm -w "$HOME/.config/repomenu/bookmarks/" -d ${bmarray[$choice]} -D;;
  esac
done
