#!/usr/bin/env bash
# -*-coding:utf-8 -*-
# Auto updated?
#   Yes
#File :
#   repomenue_bm_add
#Author :
#   The-Repo-Club [wayne6324@gmail.com]
#Github :
#   https://github.com/The-Repo-Club/
#
# Created:
#   Wed 10 March 2021, 12:34:47 PM [GMT]
# Last edited:
#   Thu 20 January 2022, 05:01:52 PM [GMT]
#
# Description:
#   <Todo>
#

result() {
  echo -n | repomenu -p "${1:-Add a bookmark:...}"
}

url="$(result "URL:")"

if [ -z "$url" ]; then
  exit
fi

title="$(result "Title:")"
tags="$(result "Tags (comma delimited):")"

bm -w "$HOME/.config/repomenu/bookmarks/" -a $url -T "$title" -t "$tags"
