#!/usr/bin/env bash

# path:       /usr/bin/repomenue_smartrun
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/repomenu-extra
# date:       2021-01-03 12:34:47.440579

asksetting() {
    options1=$(printf '%s\n' ${PATH//:/\/* } | grep "repomenu_" | sed 's|^.*/||g' | awk '!NF || !seen[$0]++')
    options2=$(printf '%s\n' ${PATH//:/\/* } | grep "repomenue_" | sed 's|^.*/||g' | awk '!NF || !seen[$0]++')
    echo -e ">>h Select App to run
$options1
$options2" | repomenu -ps 1 -l 20 -w -400 -i -h -1 -y -1 -bw 4 -q "${1:-Search...}" -x 10000
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
    CHOICE="$(asksetting)"
    [ -n "$CHOICE" ] || exit
    unset LOOPSETTING
    case $CHOICE in
    repomenu*)
        $CHOICE &
        ;;
    *)
        echo "Program terminated." && exit
        ;;
    esac
done
