#!/usr/bin/env bash
# -*-coding:utf-8 -*-
# Auto updated?
#   Yes
#File :
#   repomenue_kill
#Author:
#   The-Repo-Club [wayne6324@gmail.com]
#Github:
#   https://github.com/The-Repo-Club/
#
# Created:
#   Wed 10 March 2021, 12:34:47 PM [GMT]
# Modified:
#   Fri 21 January 2022, 02:29:56 PM [GMT]
#
# Description:
#   <Todo>
#

# Running ps to get running processes and display in repomenu.
selected="$(ps --user "$(id -u)" -F | \
            repomenu -c -i -l 20 -p "Search for process to kill:" | \
            awk '{print $2" "$11}')";

# Nested 'if' statements.  The outer 'if' statement is what to do
# when we select one of the 'selected' options listed in repomenu.
if [[ -n $selected ]]; then

    # Piping No/Yes into repomenu as a safety measure, in case you
    # select a process that you don't actually want killed.

    if rmenu -c "Kill $selected?"; then
        selpid="$(awk '{print $1}' <<< "$selected")";
        kill -9 "$selpid"
		echo "Process $selected has been killed." && exit 0
    else
		echo "Program terminated." && exit 0
    fi
fi

exit 0
